name: gaussian-blendshapes
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.3
  - python=3.9.18
  - pip=23.3.1
  - numpy=1.23.2
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - plyfile==0.7.4
    - point-cloud-utils==0.30.0
    - scikit-image==0.18.3
    - tqdm
    - scipy
    - chumpy
    - opencv-python
    - ninja
    - lpips
    - tensorboard

    

    


